language : node_js
node_js:
 - "10"
install:
- npm install
os:
 - linux

script: 
 - npm run build
 - ls

jobs:
  include:
    - stage: npm release
      if: tag =~ /v+([1-9]\d|[1-9])(\.([1-9]\d|\d)){2}$/
      deploy:
        - provider: npm
          email: "$EMAIL"
          api_key: "$TOKEN"
          skip_cleanup: true
