language : node_js
node_js:
 - "10"
install:
- npm install
os:
 - linux

script: npm run build

jobs:
  include:
    - stage: npm release
      deploy:
        provider: npm
        email: "$EMAIL"
        api_key: "$TOKEN"
        skip_cleanup: true
    - stage: github release
      deploy:
        provider: release
        skip_cleanup: true
        file: ./dist/vue.min.js
        api_key: "$github_TOKEN"
