language : node_js
node_js:
 - "10"
install:
- npm install
os:
 - linux

script: 
 - npm run build
 - ls

jobs:
  include:
    if: tag =~ 123
      - stage: npm release
        deploy:
          provider: npm
          email: "$EMAIL"
          api_key: "$TOKEN"
          skip_cleanup: true
          on:
            tags: true
