language : node_js
node_js:
 - "10"
install:
- npm install
os:
 - linux

script: npm run build

jobs:
  include:
    - stage: npm release
      deploy:
        provider: npm
        email: "$EMAIL"
        api_key: "$TOKEN"
        skip_cleanup: true
        on:
          tag: true
    - stage: github release
      deploy:
        provider: releases
        skip_cleanup: true
        file: dist/vuti.min.js
        overwrite: true
        api_key: 
          secure: "$github_TOKEN"
        on:
          tag: true
