language : node_js
node_js:
 - "10"
install:
- npm install
os:
 - linux

script: npm run build

jobs:
  include:
    - stage: npm and github release
      deploy:
        provider: npm
        email: "$EMAIL"
        api_key: "$TOKEN"
        skip_cleanup: true
      deploy:
        provider: releases
        skip_cleanup: true
        file: dist/vue.min.js
        api_key: 
          secure: "$github_TOKEN"
